FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME
# Cache and Install dependencies
COPY package.json .
COPY tsconfig.json .
RUN npm install
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "npm", "start" ]